### ISSUE TITLE
Any demo data or toy data?

### ISSUE THREAD

**Issue by sachuriga283** [EnnyvanBeest/UnitMatch#35]
Hi,

I was trying to use UnitMatch with probes other than the Neuropixel, and I am wondering if you could provide me with a sample dataset for reference? It will help me alot.

Thanks,

**Comment by EnnyvanBeest** [comment]
Hi!

We have a sample data set (Neuropixels) available via figshare (
https://figshare.com/articles/dataset/UnitMatch_Demo_-_data/24305758).
It should work with the demo-figshare that can be found in the main
unitmatch folder.

Hope this helps!

Op wo 29 nov. 2023 19:24 schreef Dizzililier ***@***.***>:
