### ISSUE TITLE
Issue with guassian filter in Python Verison

### ISSUE THREAD

**Issue by lrfreeman** [EnnyvanBeest/UnitMatch#62]
Hey Enny / Sam,

Thanks for this package. Looking forward to using it. I've come across an issue within Extract_A_unit within Extract_raw_data.py:

`#tmp = gaussian_filter(tmp, 1, radius = 2, axes = 0)`

I had to change this to:

`tmp = gaussian_filter1d(tmp, sigma = 1, radius = 2, axis = 0)`

Because the first func didn't have axes as an argument. See help doc - Perhaps I've done something wrong so let me know - https://docs.scipy.org/doc/scipy/reference/generated/scipy.ndimage.gaussian_filter.html

**Comment by Sam-Dodgson** [comment]
Hi, 
Thanks for using UnitMatch, the `gaussian_filter` function [for the later version](https://docs.scipy.org/doc/scipy/reference/generated/scipy.ndimage.gaussian_filter.html), should have the axes key word argument, however looking at the older version of SciPy [in 1.10.1 and prior](https://docs.scipy.org/doc/scipy-1.10.1/reference/generated/scipy.ndimage.gaussian_filter.html) it doesnt seem to have the axes version. 

Could you try looking at the version of SciPy and seeing if this fixes the issue?

best,
Sam

**Comment by lrfreeman** [comment]
Hi Sam,

Thanks for the quick response. I confirm I am running 1.10.1 in my conda env. I used `pip install UnitMatch` inside an exsisting conda environment and it must have not updated due to conflicts. I've created a new env and can confirm it's working now. Thanks

L
