### ISSUE TITLE
Error in filling channel position on python version 

### ISSUE THREAD

**Issue by lrfreeman** [EnnyvanBeest/UnitMatch#63]
Hey!

I'm getting an error with channel position:

![image](https://github.com/user-attachments/assets/1fdb618a-bbd1-46e7-a0de-d662808761aa)

Which is leading to a (I assume) errors down the line

![image](https://github.com/user-attachments/assets/3ed78ea5-483e-4326-86ff-2599c09a40f0)

Any advice?

**Comment by Sam-Dodgson** [comment]
Hi,

Unit match require that the channel_positions cover the full probe (as we use all of the channel in the calculations) however some spike sorters occasionally omit some inactive channel, we try to fix this my estimating the missing channel positions.
I will look into the estimation to see if I can improve it, however if you could send me the channel_positions.npy and channel_map.npy files, and give me how many channels was recorded for this session it would be very helpful for spotting and fixing this issue.

best,
Sam

**Comment by Sam-Dodgson** [comment]
With the data you sent I am not seeing any issues (both the channel_map and channel_positions seem full) 
![image](https://github.com/user-attachments/assets/bae7fb82-321a-4893-8b8a-04a861a46af4)
Could you look to see if:
1. It is the data from the other session which has bad channels
2. If the RawWaveform folder is the problem (how did you extract the raw waveforms? do what is there shape?). The spike interface method is not as well tested, and it may be the case that it does not extract all the channels for the RawWaveform input?

What the code is doing is to check that the channel_positions have the same number of channels as the extracted raw waveforms, if they don't the `fill_missing_pos` function will run and attempt to fill in the missing positions. I think your raw waveforms have a missing channel (one less than the channel_positions.npy and channel_map.npy files) which will cause this issue.

**Comment by lrfreeman** [comment]
To check whether the raw waveforms have been generated wrong I reran them with these parameters:

![image](https://github.com/user-attachments/assets/717615f8-a97c-4f23-b416-c2c2cb08c865)

I previously had nChannels at 384 and moved it to 383. Not sure exactly why I have 383 I would expect 384 if spike interface only removes the sync channel. This helped with the missing channel errors. Now it runs clean.

![image](https://github.com/user-attachments/assets/36ab22d1-e60f-4fed-a8fd-8d9a20f691df)

However I get a new error when running the next block:

![image](https://github.com/user-attachments/assets/de3a0de7-c86e-43d8-abc6-b838b3dc2e8a)

With the error being: 

![image](https://github.com/user-attachments/assets/1982886c-5fe6-43c1-b5fb-59c5f1bfa1c2)

**Comment by Sam-Dodgson** [comment]
Okay, I have encountered a similar issue before and I will look into it.
If you could send the RawWaveform folder and the good units .tsv , then I will be able to test the fix on applicable data.

I would recommend looking at the two problematic units (`plt.plot(waveform[unit, :, :, 1])` to see how the units look, as they are likely bad units, a temp fix would be to maually label them as mua in your good units .tsv file.
(Note you have to use `ClusInfo['OriginalID'][unit]` to go back to the proper unit ID, where unit is `56` and `214`)

**Comment by lrfreeman** [comment]
Sure - here are the two sessions. I will try and manually remove these clusters and see what happens. Thanks 
[25th.zip](https://github.com/user-attachments/files/16393957/25th.zip)

**Comment by Sam-Dodgson** [comment]
Hi, 
When running the data you sent I didn't have nay problems (even on the old version), however I have updated the code (PyPi and WIP branch) to refactor and fix some bugs. I believe this should fix you issue., if it doesn't I would recommend checking if those units are very bad (noise/artefact units can break the code).

please let me know if the issue remains.
