### ISSUE TITLE
using UnitMatch with data curated with Phy

### ISSUE THREAD

**Issue by nadine-saluti** [EnnyvanBeest/UnitMatch#68]
Hi,

I am interested in trying your code on my data. I have chronic recordings with 64-channel silicone probes, which I sorted with Kilosort and then manually curated with Phy. I was wondering if you could help me use your code to skip the curation steps that you propose and already run UnitMatch on phy-curated data.

Thanks,
Nadin

**Comment by EnnyvanBeest** [comment]
Hi Nadin,

It would be best if you followed the Demo script 
However, at the top, please specify  Params.RunQualityMetrics = 0, this way the curation will be skipped and if there is phy-curated data, it should automatically load the phy curated data.

A side note is that I have never tried UnitMatch with 64-channel silicone probes. I think so long as the geometry remains stable (and can be read in from the Kilosort folder), it should work. 

If the code doesn't work (again, I haven't tested it on other data than Neuropixels before), feel free to add two example kilosort folders [here](https://www.dropbox.com/scl/fo/6zzrnnwvurroa81zlyu9f/APb111YYqjxbNzsPwU6ctC8?rlkey=k0euxavg87fi1qmocnyvpz3g7&st=9lbrvksa&dl=0) and I will try to have a look at it as soon as possible.

Best,
Enny

**Comment by nadine-saluti** [comment]
Thanks for the fast reply, I will try it and update you.

**Comment by nagergo** [comment]
Hi,

First of all, thanks very much for this amazing tool!

 I also would like to use it on Phy2-curated data recorded with 128-channel and 64-channel silicon probes (and with the intan software).

Can I ask if it worked?

Many thanks in advance,
Gergo
