### ISSUE TITLE
RawWaveforms

### ISSUE THREAD

**Issue by vasilisazhukova** [EnnyvanBeest/UnitMatch#73]
Hello,
I am starting my work with Neuropixels 2.0 and try to apply UnitMatch
method for my recordings. Thank you for this method.
I have a couple of questions. I would be very thankful to you, if you
could answer them.

1. I see references to Kilosort in your paper and in the code. I
usually continue to process my data and select "good" clusters with
Phy2. Can I still use the data from Phy2 in UnitMatch pipeline or it is
better to keep kilosorted ones?

2. I have a problem with "RawWaveforms" in the pipeline. Is it possible
to obtain the two parts of the waveforms from the file "templates.npy"
of already sorted data, not from the raw ones how it is written in the
script "extract_raw_data_demo"?

Thank you in advance.

**Comment by EnnyvanBeest** [comment]
Hi,
Thanks for your interest in UnitMatch.

1. Yes, you can use whichever curation method you like. You just need to store the ‘well-isolated units’ – however you decide to define that - as a ‘1’ in the Good_ID logical vector. See: https://github.com/EnnyvanBeest/UnitMatch/blob/main/MATLAB/DEMO_UNITMATCH.m#L82
If you want the automated pipeline to not use automated quality metrics (we personally use Bombcell - https://github.com/Julie-Fabre/bombcell), just put the UMparam.RunQualityMetrics to 0. In that case, if there is phy output detected, this will be taken into account to define ‘Good_ID’. See: https://github.com/EnnyvanBeest/UnitMatch/blob/main/MATLAB/DEMO_UNITMATCH.m#L54

2. No, UnitMatch requires two waveforms, averaged from the raw data. Templates tend to be distorted, and typically you only get one template per unit from sorters. For this reason, it is best to extract the RawWaveforms as instructed. UnitMatch should handle this: https://github.com/EnnyvanBeest/UnitMatch/blob/main/MATLAB/UnitMatchPipeline/UnitMatch.m#L101 - provided you provide the (decompressed) RawDataPaths, see: https://github.com/EnnyvanBeest/UnitMatch/blob/main/MATLAB/DEMO_UNITMATCH.m#L68

If this solves your issue, please close it. However, if for some reason extract_raw_data_demo does not work, please provide the error message and the type of raw data you have?

Enny

**Comment by vasilisazhukova** [comment]
Thank you. I work in Python. Can I use the same approaches using your Python script?

**Comment by EnnyvanBeest** [comment]
Yes, in principle it works the same, although please refer to the example notebooks for python for

1. Running UnitMatch using Phy curation: https://github.com/EnnyvanBeest/UnitMatch/blob/main/UnitMatchPy/Demo%20Notebooks/UMPy_example.ipynb - note that you can overwrite 'good_units' to reflect your Phy curation, just make sure to set
`good_units_only = False` when calling `util.load_good_waveforms`, and to then subselect data that was phy curated as 'good'.

2. Example notebook for extracting the raw waveforms: https://github.com/EnnyvanBeest/UnitMatch/blob/main/UnitMatchPy/Demo%20Notebooks/extract_raw_data_demo.ipynb
