### ISSUE TITLE
GUI.py linux incompatabilities

### ISSUE THREAD

**Issue by charlesdgburns** [EnnyvanBeest/UnitMatch#79]
Hi there! big fan of the python package / wrapper -I'm slowly trying to get it to work on a headless server via the jupyter-notebook. 
Our servers are linux-based so there's a few incompatabilities I've run into so far. Hope this helps!

1.   when using gui.run_GUI() there's an error when loading themes from a Linux based server.
```Python
[58](path/to/site-packages/UnitMatchPy/GUI.py:58) theme_path = os.path.join(os.path.dirname(os.path.abspath(__file__)) , r'TkinterTheme\awthemes-10.4.0')
     [59](path/to/site-packages/UnitMatchPy/GUI.py:59) root.tk.call('lappend', 'auto_path', theme_path)
---> [60](path/to/site-packages/UnitMatchPy/GUI.py:60) root.tk.call('package', 'require', 'awdark')
     [61](path/to/site-packages/UnitMatchPy/GUI.py:61) s = ttk.Style(root)
     [62](path/to/site-packages/UnitMatchPy/GUI.py:62) s.theme_use('awdark')
```

Looks like it boils down to the path being given with backslash rather than forward slash in the line "r'TkinterTheme\awthemes-10.4.0'"
I think the solution that should work across platforms is 
```Python
theme_path = os.path.join(os.path.dirname(os.path.abspath(__file__)) , `'TkinterTheme','awthemes-10.4.0')`
```

2. a second GUI issue is incompatability of .ico, which Linux doesn't seem to like. Maybe consider using a .png for more universality? 
my temporary solution was to drop the icon for the default:
```Python
root.iconbitmap('')
```

**Comment by EnnyvanBeest** [comment]
Hi,
Thanks for the great feedback and the potential solutions. We will look into these as soon as possible!

**Comment by Sam-Dodgson** [comment]
Hi,
Sorry for taking so long, however the newest version on github work In Progress branch and the 2.20 PyPi release `pip install UnitMatchPy --update` should before be compatible with Linux based on the issues above.

Please let me know if this solves the issues or if there is any other Linux incompatibilities, as i currently cant test a Linux device to confirm this works.

**Comment by charlesdgburns** [comment]
Hi again!

Thanks for the quick update! 

I ran into other virtual monitor issues across servers which I haven't prioritiesed solving yet (so skipping the GUI), but I'll get back to you if I run into other issues. I think if any, they won't be related to the UnitMatch codebase, so I think this issue is solved :)
