### ISSUE TITLE
Key error in the original code 

### ISSUE THREAD

**Issue by vasilisazhukova** [EnnyvanBeest/UnitMatch#80]
Hello,

I ran UnitMatch code "UMPy_example" on the data from UCL course for UnitMatch block. The code was without modifications. 
Everything was fine until I wanted to save results. 
I received a key error when I ran the analysis without changes of labels in gui, with changes in gui, after replacement "matches" with "matches_manual", without this replacement. I also tryed to change the mode of util.curate_matches from "and" to "or", but this key error with ids remained. 
However, some files were saved in the output directory. 
Could you please help me to solve this error?
![error in data saving](https://github.com/user-attachments/assets/2a2ad83f-ff36-48a8-acc5-2557c5aa9474)
![data after UnitMatch](https://github.com/user-attachments/assets/da44b2b6-7e1c-4eb3-85ed-f521f9e72dec)

**Comment by cbimbo** [comment]
Hi,

Could you please check what's in `clus_info`, by printing `clus_info.keys()`?
Also, could you please check and copy/paste here your line that creates `clus_info`? It should be:
`clus_info = {'good_units' : good_units, 'session_switch' : session_switch, 'session_id' : session_id, 
            'original_ids' : np.concatenate(good_units) }`

Thanks!

**Comment by vasilisazhukova** [comment]
Sure. 
![clus_info](https://github.com/user-attachments/assets/5668e764-1977-40f7-8c87-0a00f3e7f6c5)

It looks like I have 'original_id' instead of 'original_ids', right?

**Comment by cbimbo** [comment]
Yes! Just to make sure I understand, could you please send a copy/screenshot of the line at the beginning of your notebook that's just below `# Create clus_info, contains all unit id/session related info`?

**Comment by vasilisazhukova** [comment]
Here, it is. 
![create clus_info](https://github.com/user-attachments/assets/a7ff693c-3cff-49fe-8f95-10afa47a7f68)

**Comment by vasilisazhukova** [comment]
After I replaced clus_info, I received an error in assign_unique_id
![unique_id](https://github.com/user-attachments/assets/46251691-cd16-4add-8389-88772452e0d5)

**Comment by cbimbo** [comment]
Yeah ok so I think just changing this line so it's `clus_info = {'good_units' : good_units, 'session_switch' : session_switch, 'session_id' : session_id,  'original_ids' : np.concatenate(good_units) }` should solve the issue. Let us know if not!

Not sure why this is like this though, it should be with an "s" by default.

**Comment by vasilisazhukova** [comment]
@cbimbo Thank you for your reply. Today I removed the UnitMatch environment and reinstalled the new one with commands provided here for UnitMatchPy. I restarted my PC and repeated the analysis. Again, I received key errors: _assign_new_units_ requires 'original_id' and _save_to_output_ - 'original_ids'. 
Could you please check files of these functions?

**Comment by cbimbo** [comment]
This is very confusing.
Both functions indeed have "original_ids"
-[assign_unique_id](https://github.com/EnnyvanBeest/UnitMatch/blob/ab34c08b283b634f3bb02dd961c63c4fa29a0899/UnitMatchPy/UnitMatchPy/assign_unique_id.py#L45)
- [make_match_table](https://github.com/EnnyvanBeest/UnitMatch/blob/ab34c08b283b634f3bb02dd961c63c4fa29a0899/UnitMatchPy/UnitMatchPy/save_utils.py#L44)
What branch are you on?

**Comment by Sam-Dodgson** [comment]
Hi, previous version 2.13-2.15 had some conflicts with the key errors (original_id vs original_ids) This should be fixed could you try `pip list` in your notebook to see what version of UnitMatchPy it is, and if it is not 2.16 please run `pip install UnitMatchPy --upgrade` .

**Comment by vasilisazhukova** [comment]
@Sam-Dodgson That was my case, thank you. I don't have this error after UnitMatch upgrade.
