### ISSUE TITLE
FlipDim is empty

### ISSUE THREAD

**Issue by xiaoxiong2n** [EnnyvanBeest/UnitMatch#81]
Hi Célian,
I am using UniMatch to track my 120-channel chronic recording data, but I encountered an error when running the program. The issue seems to stem from the line FlipDim = find(any(AllowFlipping,2)); in the ExtractSimilarityMetrics.m file, as it returns an empty value for my data. However, when I changed the line to FlipDim = 2;, the code appears to work.
I'm unsure if this modification is appropriate for neuron tracking in non-Neuropixel data. Could you advise whether this adjustment is valid, or if there's a better way to handle this for my setup?
Thanks,
Xiong

**Comment by xiaoxiong2n** [comment]
Hi Célian,

Thank you for your response. My channel map is as follows:
xcoords   = [ones(30,1);2*ones(30,1);3*ones(30,1);4*ones(30,1)]*200;
ycoords   = [(30:-1:1)';(30:-1:1)';(30:-1:1)';(30:-1:1)']*35;

Xiong

**Comment by xiaoxiong2n** [comment]
I have another question about setting the threshold to identify potential pairs in the MatchTable output. As shown in the attached image, for ID1=64, there are three potential pairs (ID2 = 65, 74, 77). Could you advise on how to proceed with setting the appropriate threshold to select the correct pair or narrow down the options? Thank you for your help!
![image](https://github.com/user-attachments/assets/39c76c47-d4d4-4c82-82c7-bd004d43fe6d)

**Comment by cbimbo** [comment]
Hi,

Re. channel map: I don't think the FlipDim parameter will be useful for you, as sites are far apart (I assume it's in microns). I'd set it to 0.

Re. multiple matches: you'll see that this happens often that UnitMatch gives a high probability for a neuron matching with more than one other neuron. There can be several reasons:
- This neuron really matches with only one of the n others, and you could take the highest matching probability to decide which one. Actually, this is what UM does when "assigning unique IDs", and what you can see for this neuron: only one of these three neurons shares the same unique ID (UID) as ID1 64 (it's neuron with ID2 74), and they both have a UID = 65 (you can see it in the 5th and 6th columns of your table). In short, UM sorts pairs by decreasing matching probability, and goes through them one by one to decide whether to group these neurons together under the same UID (implying they're the same neuron) or not. The rules are explained in the paper.
- On one day (or both days), this unit was split during the sorting process. Thus, these units are indeed all "the same" and you can merge them. This may be what happened with ID1 63 and 72, which match with ID2 66 and 68. You can see that UM gave them all the same UID 64. ID1 63 and 72 may have been split on day 1, and ID2 66 and 68 on day 2. You could look at them in the GUI or in Phy to check if this sounds right, and if yes, merge them in your analysis. 
- UnitMatch is wrong. Again, you could check this in the GUI or in Phy.

In general, we've found that using the unique IDs (UIDs) to track neurons and checking that things make sense in the GUI is optimal.

Hope this helps!

**Comment by xiaoxiong2n** [comment]
Great, thanks for your explanations!
