### ISSUE TITLE
UnitMatch on Matlab 

### ISSUE THREAD

**Issue by Electrophysionico** [EnnyvanBeest/UnitMatch#84]
Hello, I am trying to apply unitmatch.mat to my electrophysiological data (recorded with neuropixel 2.0 and processed on kilosort4 and bombcell). I am trying to follow single units throughout 3 days of recording. After trying with the available data provided for the NPX course 2024 I understood that the problem came from my files as the code worked perfectly for the given data. However, I did all the checks possible and apart from missing the following files: spike_pc_components.npy, prepared data.mat and threshold.npy everything is the same. I have the following error that I don´t quite understand as params.npy is in the right directory. I will take any suggestions!
![Screenshot 2024-10-21 174422](https://github.com/user-attachments/assets/1782e384-11b5-4bac-8876-5f1f3f946762)

**Comment by cbimbo** [comment]
Hi,
Could you please identify what is `datapath`? And does it exist on your computer?
Thanks!

**Comment by EnnyvanBeest** [comment]
Hi,

that path should refer to the path with the raw data (.bin and .meta) files, not the Kilosort files. 

You probably want to set:
UMparam.RawDataPath and UMparam.AllDecompPaths properly ([see here](https://github.com/EnnyvanBeest/UnitMatch/blob/main/MATLAB/DEMO_UNITMATCH.m#L66)).

Alternatively, you can make sure the params.py file in the Kilosort folder contains dat_path in the right format. On Windows the right format is:
`dat_path =r"//Path/to/data.ap.cbin"
`

Hope that clarifies things?

**Comment by Electrophysionico** [comment]
Hi, 
sorry for the mistake regarding datapath, I guess I still need to work on my programing skills.
My raw data files are .dat and .oebin (for the continuous and the metadata accordingly), could this be a problem when it comes to running the code (it worked for Bombcell). Thank you very much for your help I will try to set UMparam.RawDataPath and UMparam.AllDecompPaths properly.

**Comment by Electrophysionico** [comment]
Hello, 
I made some changes in the code but get a new error. After checking it looks like ExtractKilosortData.mat expects                                     this data [sp.spikeAmps, sp.spikeDepths, sp.templateDepths, sp.templateXpos, sp.tempAmps, sp.tempsUnW, sp.templateDuration, sp.waveforms] = templatePositionsAmplitudes(sp.temps, sp.winv, sp.ycoords, sp.xcoords, sp.spikeTemplates, sp.tempScalingAmps);
However I am missing spikeAmps, could this create the following error?
![Screenshot 2024-10-22 141302](https://github.com/user-attachments/assets/a0b74e19-6300-4d6a-b0e5-93a99f649326)
Thank you!

**Comment by EnnyvanBeest** [comment]
Hi,

Re your previous point:
no problem! Maybe it wasn't clear enough on our end.
You should be able to just change it to .dat and it should run. We have not implemented reading a .oebin yet, but this shouldn't stop you from running the code with OpenEphys data as others have ran it already on OpenEphys data. 

If you do get an error, please just reply with the error message and we'll look into it.

**Comment by EnnyvanBeest** [comment]
Regarding the last point: can you check with 
`which loadKSdir` 
whether you are using the loadKSdir provided by us (located in MATLAB\DataPreparation\? This should give tempScalingAmps as an output.

**Comment by Electrophysionico** [comment]
You were right there was an issue with loadKSdir. I fixed it and the code runs smoothly, however I have the following error that I find unlikely. Do you know what parameters I should change to at least have some good units? 
![Screenshot 2024-10-23 101703](https://github.com/user-attachments/assets/5829ce10-5cf4-4445-ab39-bfc0198a4e95)

**Comment by Electrophysionico** [comment]
Thank you!
That´s what I thought, and made a few changes and it works great.
