### ISSUE TITLE
UnitMatchPy drift correction per shank mismatches

### ISSUE THREAD

**Issue by charlesdgburns** [EnnyvanBeest/UnitMatch#85]
Hi again - ran into an issue when running UnitMatch via python at the stage of 
```Python
ov.extract_metric_scores(...)
```
leading to: 

```Python
File /UnitMatchPy/metric_functions.py:602, in appply_drift_correction_per_shank(pairs, sid, session_switch, avg_centroid, avg_waveform_per_tp, param)
    [599]/UnitMatchPy/metric_functions.py:599) if np.all(correct_shank_a == correct_shank_b) != True:
    [600]/UnitMatchPy/metric_functions.py:600)     print(f'These pairs may be bad {np.argwhere(correct_shank_a != correct_shank_b)}')
--> [602]/UnitMatchPy/metric_functions.py:602) drifts = centroid_a[:,correct_shank_a] - centroid_b[:,correct_shank_b]
    [603]/UnitMatchPy/metric_functions.py:603) drift =  np.nanmedian(drifts, axis = 1)
    [604]/UnitMatchPy/metric_functions.py:604) drift_per_shank[i,:] = drift
ValueError: operands could not be broadcast together with shapes (3,74) (3,73) 
```
The printline also outputs `These pairs may be bad [[2]]`.

As far as I can tell, these correct_shank_a and correct_shank_b are set after choosing pairs (74 candidates in this case) and are set to true everywhere, except for correct_shank_b which has a single False entry. This leads to the broadcast error when `centroid_b[:,correct_shank_b]` is shape (3,73) all of a sudden. Since centroid_a and centroid_b are already indexing out possible pairs, my **hotfix** has been to ignore this mismatch in line 602 and just perform the drift correction on all possible pairs anyways.

```Python
[602] drifts = centroid_a - centroid_b
``` 

But I'm wondering whether this is recommended? Will the bad match be caught in the statistics later?  Should we instead exclude these mismatches from drift correction (e.g. as below)?  Would appreciate advice!
```Python
[599] if np.all(correct_shank_a == correct_shank_b) != True:
            mismatch_list = np.argwhere(correct_shank_a != correct_shank_b)[0]
            print(f'These pairs may be bad {mismatch_list}, so are excluded from drift correction')
            correct_shank_a[mismatch_list]=False
            correct_shank_b[mismatch_list]=False
``` 

I can tell that the decision to run drift_correction per shank is being made by the function `test_matches_per_shank(...)` which also flags  this mismatch but doesn't seem to handle it or change the decision to e.g. perform basic drift_correction.

**Comment by Sam-Dodgson** [comment]
Hi, 
Sorry you are having the error here are my responses/questions:
1. You can try running on the detailed version notebook and use `best_drift = False`  in the `drift_n_sessions(....)` functions, as per-shank correction is not essential.
2. This seems to be a very odd edge case which this function is catching, have you checked the parameters for the number of shanks and the shank distance are correct for you setup?
3. Any bad matches would be largely ignored as we are using the median for drift corrections (as that is stable to a few mismatches being in the data at this point, the only problem is if it is in the per shank case where there are few candidate matches on that shank!) 
4. Thank you for the suggestions will look at implement one so this edge case gets automatically handled in the future!

**Comment by charlesdgburns** [comment]
Thanks for the super quick response!

1. This looks like a good solution for now. Thanks!

2. For some reason I didn't realise this - I'm analysing a dataset with Neuropixel 1.0 probes. So doesn't make sense at all to split data 'per shank'.  Do you know if there are other parameters I ought to change with this probe? (are you planning on implementing multiple probes in the get_default_params(...) function?)

That said, I get the exact same error when I set `no_shanks=1`. When I further set `shank_distance=0` I get another error, however: 
```Python
File /UnitMatchPy/metric_functions.py:771, in drift_n_sessions(candidate_pairs, session_switch, avg_centroid, avg_waveform_per_tp, total_score, param, best_match, best_drift)
    [769]/UnitMatchPy/metric_functions.py:769) if test_matches_per_shank(pairs, avg_centroid, did, param) == True and best_drift == True:
    [770]/UnitMatchPy/metric_functions.py:770)     drifts = np.zeros( (n_sessions - 1, param['no_shanks'], 3)) 
--> [771]s/UnitMatchPy/metric_functions.py:771)     drifts[did,:,:], avg_waveform_per_tp, avg_centroid = appply_drift_correction_per_shank(pairs, did, session_switch, avg_centroid, avg_waveform_per_tp, param)
    [772]/UnitMatchPy/metric_functions.py:772)     print(f'Done drift correction per shank for session pair {did+1} and {did+2}')
    [773]/UnitMatchPy/metric_functions.py:773) else:

ValueError: could not broadcast input array from shape (4,3) into shape (1,3)
```
which looks like it stems from a hardcoded 4 in line 590 of metric_functions.py:
```Python
[590]    drift_per_shank = np.zeros([4,3])
```
This went away when I replaced the 4 with n_shanks, but I then run into another error which was more obscure (but might also be related to other areas of the code expecting a 4-shank probe).

```Python 
File/UnitMatchPy/overlord.py:128, in extract_metric_scores(extracted_wave_properties, session_switch, within_session, param, niter)
    [125]/maze_ephys/lib/python3.12/site-packages/UnitMatchPy/overlord.py:125) param['n_expected_matches'] = np.sum( (total_score > thrs_opt).astype(int))
    [126]/maze_ephys/lib/python3.12/site-packages/UnitMatchPy/overlord.py:126) prior_match = 1 - ( param['n_expected_matches'] / len(include_these_pairs))
--> [128/maze_ephys/lib/python3.12/site-packages/UnitMatchPy/overlord.py:128) thrs_opt = np.quantile(total_score[include_these_pairs_idx.astype(bool)], prior_match)
    [129]/maze_ephys/lib/python3.12/site-packages/UnitMatchPy/overlord.py:129) candidate_pairs = total_score > thrs_opt
    [131]/maze_ephys/lib/python3.12/site-packages/UnitMatchPy/overlord.py:131) return total_score, candidate_pairs, scores_to_include, predictors

ValueError: Quantiles must be in the range [0, 1]
```
Hope this might help with future debugging.

**Comment by EnnyvanBeest** [comment]
I'll briefly comment on your above question and let @Sam-Dodgson do the rest.

We will not implement multiple probes because in our view you only ever want to match neurons that are on one probe and recorded chronically. On different probes or with acute insertions of the same probe, where the probe is not at least relatively stable in the brain (apart from some minor drift), there is no way that you will find the same neurons. 

That's why we think it's better to just run the UnitMatch code separately for different chronically implanted probes.

**Comment by charlesdgburns** [comment]
Further tracking the `Quantiles must be in the range [0,1]` error during basic drift correction I found a bug [here](https://github.com/EnnyvanBeest/UnitMatch/blob/ab34c08b283b634f3bb02dd961c63c4fa29a0899/UnitMatchPy/UnitMatchPy/metric_functions.py#L550C5-L550C87).

```Python
[550] avg_waveform_per_tp[2,session_switch[sid+1]:session_switch[sid]+2,:,:] += drift[2]
#should be                                                                                                v
[550]  avg_waveform_per_tp[2,session_switch[sid+1]:session_switch[sid+2],:,:] += drift[2]
```

This fixes issues when I set `best_drift = False` as was suggested above.

I still run into the initial mismatch issue which I had.

**Comment by Sam-Dodgson** [comment]
Hi, I have updated the code so this issues should be fixed (either use the Work in progress branch or `pip install UnitMatchPy--upgrade`, please let me know if any of these issues remain on the new branches and I will look into it!

**Comment by charlesdgburns** [comment]
Hi again - I've just managed to run through all our data with the fixes with no issues!

Thanks a lot for the quick responsiveness and help!
