### ISSUE TITLE
cannot follow a single unit through 3 recordings 

### ISSUE THREAD

**Issue by Electrophysionico** [EnnyvanBeest/UnitMatch#87]
For a couple of days I have been trying to follow a single (good) unit through 3 recordings.
However I can´t seem to use the UnitMatch outputs correctly for the different modules described here.
I was then wondering if there was an available code to follow a single unit through several recordings displaying the activity, waveform etc of this unit for two or more recordings.
These are the outputs that i get: clusinfo, MatchTable, UMparam, WaveformInfo, and UniqueIdConversion

**Comment by EnnyvanBeest** [comment]
Could you give a bit more details on your experimental set-up? If you're trying to track a single good unit it does not sound like you are using Neuropixels probes? UnitMatch is a software optimized for chronic high-density probes recordings, specifically Neuropixels, where you can record a large number of units simultaneously across many days. 

Assuming this is what you have, and you ran the code as described in one of the demos for the Matlab and/or Python version, UniqueIDConversion should contain the Unique ID (UID) for every neuron across all recordings, as well as the original ID that was given by the input you (or Kilosort) provided. The GUIs can be used to display the waveforms (and some functional activity properties), or you can load the data in other software (e.g. phy) to look at the activity for each of the neurons. Of course eventually you can use the UniqueIDConversion to look at the neural activity for the neuron in different recordings, this depends on your specific experiment.

If you have a different type of probe, UnitMatch may or may not work. As it is data driven it may be difficult to generate probability distributions when there is not enough data. In the Matlab version, you can try to use the [probability distributions we provided instead](https://github.com/EnnyvanBeest/UnitMatch/blob/main/MATLAB/UnitMatchPipeline/UnitMatchModel.mat) by setting` UMparam.ApplyExistingBayesModel = 1` [here](https://github.com/EnnyvanBeest/UnitMatch/blob/main/MATLAB/UnitMatchPipeline/DefaultParametersUnitMatch.m#L72
).

**Comment by Electrophysionico** [comment]
Yes sorry I am using Neuropixels 2.0 and open ephys to record. I phrased the question a bit wrongly, i wanted to know how could I match single units through several recordings so i could investigate their activity during several days. But i might just load the data in phy to investigate such activity if it´s possible

**Comment by EnnyvanBeest** [comment]
I think I see what you mean (although not entirely sure, so correct me if I'm wrong).

The GUIs work for pairs of neurons. In the Matlab version you can use functions[ to evaluate the output](https://github.com/EnnyvanBeest/UnitMatch/blob/main/MATLAB/DEMO_UNITMATCH.m#L108), including a GUI to go through pairs of units and visualize their waveform and some basic activity. 
If you used the tracking algorithm, you can use the UniqueIDConversion to identify the neurons with the same ID across all recordings, these are your 'single units across multiple recordings'. 
For example, you can plot the waveforms for a sample of UniqueIDs like this:
```
%% Example code to plot waveforms after UnitMatch:
GoodIdx = logical(UniqueIDConversion.GoodID); % Good units only

[UID,id1,id2] = unique(UniqueIDConversion.UniqueID(GoodIdx)); % Find unique IDs

TrackedID = find(arrayfun(@(X) sum(id2==X)>1,unique(id2))); % number of neurons tracked
if numel(TrackedID)>25 % Don't overload the plotting, just take 25 examples
    TrackedId = datasample(TrackedID,25,'replace',false);
end

figure('name','ExampleWaveforms')
for unitid = 1:numel(TrackedId)
    subplot(ceil(sqrt(numel(TrackedId))),round(sqrt(numel(TrackedId))),unitid) % subplot
    hold on
    % all neurons with this UID
    tmpwaveform = nanmean(WaveformInfo.ProjectedWaveform(:,id2==TrackedID(unitid),:),3); %Average over two halves of recording
    plot(tmpwaveform)
    xlabel('Time')
    ylabel('mV')
    makepretty
    hold off

end
```

Similarly, you can go back to the kilosort data, and find the spikes for a particular neuron in each recording, for example to find the average firing rate:

```
%% Firing rate of a neuron across recordings
RecSes = UniqueIDConversion.recsesAll(GoodIdx); % Recording session for good units
OriClusID = UniqueIDConversion.OriginalClusID(GoodIdx); % Original ClusterID
timeBinSize = 0.1% % per 100ms
timeEdges = -timeBinSize/2:timeBinSize:max(sp.st)+timeBinSize/2;% Define timebins

figure('name','FR')
for unitid = 1:numel(TrackedId)
    subplot(ceil(sqrt(numel(TrackedId))),round(sqrt(numel(TrackedId))),unitid) % subplot
    hold on

    
    % all neurons with this UID
    Idx = find(UniqueIDConversion.UniqueID(GoodIdx) == UID(TrackedId(unitid)));

    spikesForNeuron = nan(1,numel(Idx));
    % Their recording:
    for iidx = 1:numel(Idx)
        sp = loadKSdir(UMparam.KSDir{RecSes(Idx(iidx))});
      
        spikesForNeuron(iidx) = nanmean(histcounts(sp.st(sp.clu==OriClusID(Idx(iidx))),timeEdges))./timeBinSize;
    end
    scatter(RecSes(Idx),spikesForNeuron,20,[0 0 0],'filled')
    xlabel('Recording')
    ylabel('spikes/sec')
    makepretty
    hold off

end
```

I hope this helps.

**Comment by Electrophysionico** [comment]
Thank you this helped me visualize the units´ waveforms and spikes way better. I have a couple of other questions tell me if I should ask them in a new issue. I am trying to load the UnitMatch data on phy but can´t seem to open the GUI to do so (I followed the instructions on phy and UnitMatch git but arriving at the last step with "phy  template-gui params.py" or "phy template-gui config.yml" I get the error that there is not such file even though it is in the directory. Thus, I was wondering if it is a known issue or not and if there is a way to tackle it. My second question is related to an issue that I had before and encounter again. When it comes to run UnitMatch it says that I do not have good units but after checking on Phy I can see that Bombcell labeled good units. I have no clue on what I should do on the matter. Thank you for your help !

**Comment by EnnyvanBeest** [comment]
I think the best place to ask these questions in the future would be in the https://github.com/EnnyvanBeest/UnitMatch/discussions, since these are indeed not really related to issues with the UnitMatch code. Another place to ask general Neuropixels analysis questions would be in the [Neuropixels slack. ](https://neuropixelsgroup.slack.com/join/shared_invite/zt-2c8u0k21u-CC4wSkb8~U_Fkrf3HHf_kw#/shared-invite/email) But for now I'm happy to answer them here:

Your first question seems to be phy-related. My best guess would be that you're not opening running that line of code while in the folder where that params.py is stored? Make sure to 'cd' to that directory first. If that's not the answer, please refer to the phy Github page or Neuropixels slack for further questions on this toolbox.

For the second question, I would inspect the clusinfo struct that goes into the UnitMatch function. Does `clusinfo.Good_ID` match what you expect from Bombcell results? If not, something may go wrong in the preprocessing. You can always prepare clusinfo yourself rather than using the provided preprocessing scripts - these were extensively tested using SpikeGLX data, but may not work well with your pipeline? [The demo describes how to prepare clusinfo yourself. ](https://github.com/EnnyvanBeest/UnitMatch/blob/main/MATLAB/DEMO_UNITMATCH.m#L79). If there's a specific problem with the UnitMatch code you run into, please create a new issue with some example error message / screen shots of the clusinfo struct. This will help us understand what goes wrong and hopefully debug the issue.

**Comment by Electrophysionico** [comment]
Thank you for taking the time to answer to all my questions.
I will try and check your suggestions 
I will close this issue

**Comment by mengyuliu-code** [comment]
Hi there,
I am trying to do matching for 3 or more recording sessions in python. I wonder if there is a function for that?

-Mengyu
