### ISSUE TITLE
Index exceeds the number of array elements

### ISSUE THREAD

**Issue by Electrophysionico** [EnnyvanBeest/UnitMatch#90]
While trying different ways to run UnitMatch I stumbled upon this recurrent error.
More precisely I have Neuropixels 2 data that I spikesort with kilosort 4 and then run Bombcell for the RawWaveforms. I have been doing a manual curation on Phy2 to take out clusinfo. Do you have an idea of the reason of this error and how I can fix it? Thank you!

![Screenshot 2024-11-07 185331](https://github.com/user-attachments/assets/98e36a7a-1a50-4761-976d-f2fd16bb0c8d)

**Comment by EnnyvanBeest** [comment]
I can't replicate this error myself. Could you share example kilosort data for which this happens [here](https://www.dropbox.com/scl/fo/6zzrnnwvurroa81zlyu9f/APb111YYqjxbNzsPwU6ctC8?rlkey=k0euxavg87fi1qmocnyvpz3g7&st=ajz2pb93&dl=0)? Thanks!

**Comment by Electrophysionico** [comment]
You should find the data on the link

**Comment by EnnyvanBeest** [comment]
For me that runs just fine with your data. Can you please try the 'workinprogress' branch? Please set `UMparam.RunQualityMetrics = 1 ` here https://github.com/EnnyvanBeest/UnitMatch/blob/WorkInProgress/MATLAB/DEMO_UNITMATCH.m#L58 if you want to have phy curation used.
Can you let me know if the code on workinprogress branch works for you? In that case I'll pull it to main.

**Comment by Electrophysionico** [comment]
I have the same issue with the code you provided me

**Comment by EnnyvanBeest** [comment]
Could you please check which loadKSDir is used when you run 'which loadKSdir' after this error?

**Comment by Electrophysionico** [comment]
This is the directory that i have after running  'which loadKSdir' after this error

  \Documents\MATLAB\UnitMatch-main\MATLAB\DataPreparation\loadKSdir.m

**Comment by EnnyvanBeest** [comment]
I'm afraid that I really don't know what's going on. For me the version of UnitMatch on the work in progress branch works on your data (up to the point where it needs the raw waveforms, as I don't have your raw waveforms or raw data). If you're sure you're running that version (which means, [pulled/redownloaded the code in this branch](https://github.com/EnnyvanBeest/UnitMatch/tree/WorkInProgress/MATLAB), I really don't know how to explain it. 

Since it's just the Kilosort extraction I'd recommend you prepare UnitMatch inputs using the 'IF NOT' option described here: https://github.com/EnnyvanBeest/UnitMatch/blob/WorkInProgress/MATLAB/DEMO_UNITMATCH.m#L67

**Comment by Electrophysionico** [comment]
Thank you very much for your help I will try to figure it out!

**Comment by ryanlash** [comment]
Hi! I have also been experiencing the same issue, where the templateDepths doesn't index correctly. Is this possibly an issue with spikes? I can also upload kilosort4 output files if that's helpful too.

**Comment by EnnyvanBeest** [comment]
Hi,
Could you please confirm that you've tried the WorkInProgress branch as suggested above? Alternatively, you can repull the main branch, as I have just pulled the work in progress branch (that contains bug- and issue-fixes) to the main branch.

If that still doesn't work, it would indeed bye helpful to send some kilosort4 output files to that dropbox link above, please drop them in a subfolder with your github name if possible?

Thanks!

**Comment by ryanlash** [comment]
Yes originally tried with main branch then after the error, read this thread and tried the work in progress branch. I just uploaded three sessions of ks4 output to the dropbox under the UnitMatchDebug_ryanlash folder. Thank you!

**Comment by EnnyvanBeest** [comment]
There seems to be a problem with your clutser_group.tsv files. There are only 11 units (all defined as noise), while there are 90 unique units in the spike_clusters.npy. I'm not sure what's going on but this is likely upstream and not an issue for UnitMatch. You could perhaps try analyzing the data without manual curation (if you're using bombcell anyway, it may not necessary) and run it like that first to see whether the manual curaiton you are doing causes some issues.

**Comment by ryanlash** [comment]
So I'm attempting to run it on three sessions I just ran through KS4 but keep on encountering this error despite there being good units labeled through BC. Do I need to label them as "Good" in phy before running?
Error using UnitMatch (line 75)
No good units in these recordings (yet asking for it). check!

Error in DEMO_UNITMATCH (line 105)
[UniqueIDConversion, MatchTable, WaveformInfo, UMparam] = UnitMatch(clusinfo, UMparam);
                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by EnnyvanBeest** [comment]
You can overwrite clusinfo.Good_ID before running UnitMatch, but basically it's telling you you don't have any good units. If you haven't removed your earlier phy results, it will still load these. 
I've just pushed some changes [on the workinprogress branch](https://github.com/EnnyvanBeest/UnitMatch/tree/WorkInProgress), but probably you just have to make sure your output files are loaded the way you think they are. Maybe just go in the extractkilosortdata script in debug mode, and check what's happening?
